apiVersion: v1
kind: Namespace
metadata:
  name: taskmanager

---

# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          command: ["mongod", "--auth", "--bind_ip_all"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpassword

---

# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: taskmanager
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

# TaskService Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskservice
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskservice
  template:
    metadata:
      labels:
        app: taskservice
    spec:
      containers:
        - name: taskservice
          image: knutekje/taskservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://root:rootpassword@mongodb.taskmanager.svc.cluster.local:27017/taskdb"

---

# TaskService Backend Service
apiVersion: v1
kind: Service
metadata:
  name: taskservice
  namespace: taskmanager
spec:
  type: ClusterIP
  selector:
    app: taskservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# React Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: knutekje/react-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://taskservice.taskmanager.svc.cluster.local/api"

---

# React Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: taskmanager
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
